// === THIS FILE WAS GENERATED BY A PROGRAM EDITS WILL BE OVERWRITTEN ===
// scripts/update_offsets.sh (you may optionaly add this as a pre commit hook, maybe this should be a cmake custom
// target?)

// DecaGames_RotMG_SocketManger__GotMessageHandler
#define OFFSET_GOT_MSG 0x1710250
// DecaGames_RotMG_SocketManger__SendMessage
#define OFFSET_SEND_MSG 0x1711CB0
// DecaGames_RotMG_CameraManager__Update
#define OFFSET_CAMERA_UPDATE 0x1219C80
// FJBJOOHPBDL__MAEKPBAECML
#define OFFSET_INIT_SCREEN 0x1E06C80
// CameraManger_ONKBCEJOCHD
#define OFFSET_CAMERA_OFFSET_UPDATE 0x1218170
// Com_LuisPedroFonseca_ProCamera2D__ResizeCameraToPixelPerfect
#define OFFSET_PC2D_RESIZE 0x2751510
